#!/usr/bin/python

def basic_Q_features(): # from questionnaires
    return [ # 30 features
        "BASIC_Q_EHI_Sum", 
        "BASIC_Q_SF36_PhysicalFunct", 
        "BASIC_Q_SF36_PhysicalLimit", 
        "BASIC_Q_SF36_EmotionalWell", 
        "BASIC_Q_SF36_EmotionalLimit", 
        "BASIC_Q_SF36_Energy", 
        "BASIC_Q_SF36_SocialFunc", 
        "BASIC_Q_SF36_Pain", 
        "BASIC_Q_SF36_GeneralHealth", 
        "BASIC_Q_SF36_Physical", 
        "BASIC_Q_SF36_Mental", 
        "BASIC_Q_PSQI_SleepQuality", 
        "BASIC_Q_PSQI_SleepLatency", 
        "BASIC_Q_PSQI_SleepDuration", 
        "BASIC_Q_PSQI_SleepEfficiency", 
        "BASIC_Q_PSQI_SleepDisturbance", 
        "BASIC_Q_PSQI_SleepMedication", 
        "BASIC_Q_PSQI_DaytimeDysfunc", 
        "BASIC_Q_PSQI_Sum", 
        "BASIC_Q_IPAQ_MET", 
        "BASIC_Q_BFI_Extraversion", 
        "BASIC_Q_BFI_Agreeableness", 
        "BASIC_Q_BFI_Conscientiousness", 
        "BASIC_Q_BFI_EmotionalStability", 
        "BASIC_Q_BFI_Intellect", 
        "BASIC_Q_MSPSS_Sum", 
        "BASIC_Q_CogFailure_Sum", 
        "BASIC_Q_Beck_Anxiety", 
        "BASIC_Q_Beck_Depression", 
        "BASIC_Q_MOCA_SUM"
    ]

def ST_features(): # from standardized tests
    return [ # 16 features
        "LANGUAGE_ST_SCALED_SIMILARITY", 
        "LANGUAGE_ST_SCALED_VOCABULARY", 
        "LANGUAGE_ST_SCALED_INFORMATION", 
        "MEMORY_ST_SCALED_AudImm", 
        "MEMORY_ST_SCALED_VisImm", 
        "MEMORY_ST_SCALED_WorMem", 
        "MEMORY_ST_SCALED_LogMemI", 
        "MEMORY_ST_SCALED_LetNumSeq", 
        "MEMORY_ST_SCALED_FamPicI", 
        "MEMORY_ST_SCALED_VerPairI", 
        "MEMORY_ST_SCALED_FacI", 
        "MEMORY_ST_SCALED_SpaForward", 
        "MEMORY_ST_SCALED_SpaBackward", 
        "MOTOR_ST_SCALED_FineMotor", 
        "MOTOR_ST_SCALED_Balance", 
        "MOTOR_ST_SCALED_ProcessingSpeed"    
    ]

def ST_feat_raw(): 
    return [ # 38 features
        "LANGUAGE_ST_RAW_SIMILARITY",
        "LANGUAGE_ST_RAW_VOCABULARY",
        "LANGUAGE_ST_RAW_INFORMATION",
        "LANGUAGE_ST_RAW_SUM",
        "MEMORY_ST_RAW_AudImm",
        "MEMORY_ST_RAW_VisImm",
        "MEMORY_ST_RAW_ImmMem",
        "MEMORY_ST_RAW_WorMem",
        "MEMORY_ST_RAW_LogMemI",
        "MEMORY_ST_RAW_FacI",
        "MEMORY_ST_RAW_VerPairI",
        "MEMORY_ST_RAW_FamPicI",
        "MEMORY_ST_RAW_LetNumSeq",
        "MEMORY_ST_RAW_SpaForward",
        "MEMORY_ST_RAW_SpaBackward",
        "MEMORY_ST_RAW_SpaTotal",
        "MOTOR_ST_RAW_BPrestHigh",
        "MOTOR_ST_RAW_BPrestLow",
        "MOTOR_ST_RAW_HRrest",
        "MOTOR_ST_RAW_HEIGHT",
        "MOTOR_ST_RAW_WEIGHT",
        "MOTOR_ST_RAW_BMI",
        "MOTOR_ST_RAW_WHR",
        "MOTOR_ST_RAW_AerobicRating",
        "MOTOR_ST_RAW_FunctionalReaching",
        "MOTOR_ST_RAW_WorseLegEyeOpen",
        "MOTOR_ST_RAW_BestLegEyeOpen",
        "MOTOR_ST_RAW_WorseLegEyeClose",
        "MOTOR_ST_RAW_BestLegEyeClose",
        "MOTOR_ST_RAW_PegboardDominant",
        "MOTOR_ST_RAW_PegboardNondominant",
        "MOTOR_ST_RAW_PegboardBoth",
        "MOTOR_ST_RAW_PegboardSum",
        "MOTOR_ST_RAW_PegboardAssemble",
        "MOTOR_ST_RAW_SymbolSearch",
        "MOTOR_ST_RAW_SymbolCoding",
        "MOTOR_ST_RAW_GripMvcL",
        "MOTOR_ST_RAW_GripMvcR"
    ]